disabled_rules:
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - vertical_parameter_alignment
  - closure_parameter_position
  - todo
  - superfluous_disable_command

opt_in_rules:
  - static_operator
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - fatal_error_message
  - unneeded_parentheses_in_closure_argument
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation
  - joined_default_parameter
  - contains_over_first_not_nil
  - override_in_extension
  - private_action
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - sorted_first_last

line_length: 120

type_body_length:
  - 300 
  - 300 
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - vertical_parameter_alignment
  - closure_parameter_position
  - todo
  - superfluous_disable_command

file_length:
  warning: 400 
  error: 400 
  ignore_comment_only_lines: true

nesting:
  type_level: 3

cyclomatic_complexity:
  ignores_case_statements: true
